---
name: "OPA-action (manual)"
on: [workflow_dispatch]

jobs:
  conftest:
    name: Dogfooding OPA-action
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Dogfooding OPA-action
        uses: ./
